// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqpjzfcbnxzsupciyrnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xcGp6ZmNibnh6c3VwY2l5cm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMDUwNzIsImV4cCI6MjA3MDg4MTA3Mn0.Xlg5eAyAleVZB3yT4zo8J0TAYfZm5scuq-13OX5lASc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});